spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.woxodupoklndupxotmhp
spring.datasource.password=Telkomsel12.
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.open-in-view=false
spring.jmx.enabled=false
spring.datasource.driver-class-name=org.postgresql.Driver
spring.main.lazy-initialization=true
server.port=8081

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.hikari.data-source-properties.ssl=true
spring.datasource.hikari.data-source-properties.sslmode=require
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.initialization-fail-timeout=10000
spring.datasource.hikari.connection-timeout=10000
spring.datasource.hikari.validation-timeout=5000